export const coursesData = [
  {
    id: 1,
    title: "Huquqiy bilimlarni oshirish",
    category: "Tanlov",
    instructor: "Raxmonov Zafarjon Zayniddinovich",
    duration: "4 soat",
    topics: 2,
    language: "O'zbek",
    rating: 0,
    students: 0,
    date: "2025-07-28 15:54:33",
    description:
      "Oliy ta'lim muassasalari pedagog kadrlarini qayta tayyorlash va malakasini oshirish kursining maqsadi pedagog kadrlarning ўқув-tarbiyaviy jaraёnlarni yuqsak ilmiy-metodik darajada tashkillashlari uchun zarur buladigan kasbiy bilim, kўnikma va malakalarini muntazam yangilash, malaka talablariv, ўқuv rejalari va dasturlari asosida ularning kasbiy kompetentligi va pedagogik mahoratini doimiy rivojlantirish tizimini tashkillash iborat.",
    objectives: [
      "Pedagog kadrlarning kasbiy kompetentligini oshirish",
      "Zamonaviy ta'lim texnologiyalarini o'rgatish",
      "Ilmiy-tadqiqot faoliyatini rivojlantirish",
      "Xalqaro tajribalar bilan tanishish",
    ],
    modules: [
      {
        title: "Huquqiy asoslar",
        duration: "1 soat",
        topics: ["Konstitutsiya asoslari", "Fuqarolik huquqi", "Mehnat huquqi"],
      },
      {
        title: "Amaliy mashg'ulotlar",
        duration: "3 soat",
        topics: ["Hujjatlar bilan ishlash", "Huquqiy maslahatlar", "Sud amaliyoti"],
      },
    ],
  },
  {
    id: 2,
    title: "Adliya xodimlari faoliyatida stress-menejmenti",
    category: "Tanlov",
    instructor: "Xojimuhamedova Dilbar Rixsibayevna",
    duration: "6 soat",
    topics: 3,
    language: "O'zbek",
    rating: 0,
    students: 0,
    date: "2025-07-25 10:30:00",
    description:
      "Adliya xodimlari uchun stress boshqaruvi va psixologik barqarorlikni ta'minlash bo'yicha maxsus kurs. Kurs davomida stress omillari, ularning ta'siri va bartaraf etish usullari o'rgatiladi.",
    objectives: [
      "Stress omillarini aniqlash va tahlil qilish",
      "Psixologik barqarorlikni saqlash usullari",
      "Ishda samaradorlikni oshirish",
      "Shaxsiy rivojlanish strategiyalari",
    ],
    modules: [
      {
        title: "Stress nazariyasi",
        duration: "2 soat",
        topics: ["Stress turlari", "Psixologik ta'sir", "Fiziologik o'zgarishlar"],
      },
      {
        title: "Stress boshqaruvi",
        duration: "2 soat",
        topics: ["Relaksatsiya texnikalari", "Vaqtni boshqarish", "Muloqot ko'nikmalari"],
      },
      {
        title: "Amaliy mashg'ulotlar",
        duration: "2 soat",
        topics: ["Vaziyatli masalalar", "Guruh ishlari", "Individual konsultatsiyalar"],
      },
    ],
  },
  {
    id: 3,
    title: "Adliya xodimlari faoliyatida nizolarni bartaraf etish",
    category: "Tanlov",
    instructor: "Xojimuhamedova Dilbar Rixsibayevna",
    duration: "6 soat",
    topics: 4,
    language: "O'zbek",
    rating: 0,
    students: 0,
    date: "2025-07-20 14:15:00",
    description:
      "Adliya tizimida yuzaga keladigan nizolarni hal etish, mediatsiya va muzokaralar olib borish bo'yicha professional ko'nikmalarni rivojlantirish kursi.",
    objectives: [
      "Nizolarni tahlil qilish metodlari",
      "Mediatsiya jarayonini boshqarish",
      "Muzokaralar olib borish ko'nikmalari",
      "Konflikt situatsiyalarini hal etish",
    ],
    modules: [
      {
        title: "Nizolar nazariyasi",
        duration: "1.5 soat",
        topics: ["Nizolar turlari", "Sabablari", "Rivojlanish bosqichlari"],
      },
      {
        title: "Mediatsiya asoslari",
        duration: "2 soat",
        topics: ["Mediator roli", "Jarayon bosqichlari", "Texnikalar"],
      },
      {
        title: "Muzokaralar",
        duration: "1.5 soat",
        topics: ["Strategiyalar", "Taktikalar", "Psixologik aspektlar"],
      },
      {
        title: "Amaliy mashg'ulotlar",
        duration: "1 soat",
        topics: ["Rol o'yinlari", "Vaziyatli masalalar", "Tahlil"],
      },
    ],
  },
  {
    id: 4,
    title: "HR menejmenti - zamonaviy yondashuv",
    category: "Tanlov",
    instructor: "Karimova Sevara Akmalovna",
    duration: "12 soat",
    topics: 6,
    language: "O'zbek",
    rating: 0,
    students: 0,
    date: "2025-07-15 09:00:00",
    description:
      "Zamonaviy HR menejmenti yondashuvlari, kadrlar bilan ishlash, motivatsiya tizimi va xodimlarni rivojlantirish bo'yicha keng qamrovli kurs.",
    objectives: [
      "Zamonaviy HR strategiyalarini o'rganish",
      "Kadrlarni tanlash va baholash",
      "Motivatsiya tizimini yaratish",
      "Xodimlarni rivojlantirish dasturlari",
    ],
    modules: [
      {
        title: "HR strategiyasi",
        duration: "2 soat",
        topics: ["Strategik rejalashtirish", "HR analitika", "Tashkiliy madaniyat"],
      },
      {
        title: "Kadrlar tanlovi",
        duration: "2 soat",
        topics: ["Suhbat texnikalari", "Baholash usullari", "Onboarding"],
      },
      {
        title: "Motivatsiya",
        duration: "2 soat",
        topics: ["Motivatsiya nazariyalari", "Rag'batlantirish tizimi", "KPI"],
      },
      {
        title: "Rivojlantirish",
        duration: "2 soat",
        topics: ["Ta'lim dasturlari", "Karyera rejalashtirish", "Mentoring"],
      },
      {
        title: "Ishlash samaradorligi",
        duration: "2 soat",
        topics: ["Baholash tizimi", "Feedback", "Coaching"],
      },
      {
        title: "Amaliy loyiha",
        duration: "2 soat",
        topics: ["Loyiha ishlab chiqish", "Taqdimot", "Muhokama"],
      },
    ],
  },
]

export const specialistsData = [
  {
    id: 1,
    name: "Raxmonov Zafarjon Zayniddinovich",
    position: "Yuridik fanlar doktori, professor",
    specialization: "Konstitutsiya huquqi, Ma'muriy huquq",
    experience: "25 yil",
    education: "Toshkent davlat yuridik universiteti",
    courses: ["Huquqiy bilimlarni oshirish", "Konstitutsiya asoslari"],
    achievements: [
      "50+ ilmiy maqola muallifi",
      "10+ darslik va qo'llanma muallifi",
      "Xalqaro konferensiyalar ishtirokchisi",
    ],
    image: "/placeholder.svg?height=300&width=300",
  },
  {
    id: 2,
    name: "Xojimuhamedova Dilbar Rixsibayevna",
    position: "Psixologiya fanlari nomzodi, dotsent",
    specialization: "Yuridik psixologiya, Stress menejmenti",
    experience: "18 yil",
    education: "O'zbekiston Milliy universiteti",
    courses: ["Stress-menejmenti", "Nizolarni bartaraf etish"],
    achievements: ["30+ ilmiy maqola muallifi", "Psixologik konsultant sertifikati", "Mediatsiya bo'yicha mutaxassis"],
    image: "/placeholder.svg?height=300&width=300",
  },
  {
    id: 3,
    name: "Karimova Sevara Akmalovna",
    position: "Iqtisodiyot fanlari nomzodi",
    specialization: "HR menejmenti, Tashkiliy psixologiya",
    experience: "15 yil",
    education: "Toshkent davlat iqtisodiyot universiteti",
    courses: ["HR menejmenti", "Liderlik ko'nikmalari"],
    achievements: ["HR sertifikatlari (SHRM, CIPD)", "20+ kompaniyada konsultant", "Biznes-trening eksperti"],
    image: "/placeholder.svg?height=300&width=300",
  },
  {
    id: 4,
    name: "Abdullayev Jasur Karimovich",
    position: "Yuridik fanlar nomzodi",
    specialization: "Jinoyat huquqi, Sud ekspertizasi",
    experience: "20 yil",
    education: "Toshkent davlat yuridik universiteti",
    courses: ["Jinoyat huquqi asoslari", "Sud ekspertizasi"],
    achievements: [
      "Sud eksperti sertifikati",
      "40+ sud jarayonlari ishtirokchisi",
      "Jinoyat huquqi bo'yicha mutaxassis",
    ],
    image: "/placeholder.svg?height=300&width=300",
  },
]
